In [1]:
# Derived Variable
# Description
# The given dataset 'cust_rating' has 3 columns i.e 'rating', ' food_rating', 'service_rating'. Create a new variable 'avg_rating'.


import pandas as pd
cust_rating = pd.read_csv('https://media-doselect.s3.amazonaws.com/generic/GvOkzy5MLdy9zJ8vXMArwpRvN/rating_final.csv')

cust_rating['avg_rating'] = round(cust_rating.loc[:,[c for c in cust_rating.columns if "rating" in c]].mean(axis=1))

print(cust_rating.head(10))

  userID  placeID  rating  food_rating  service_rating  avg_rating
0  U1077   135085       2            2               2         2.0
1  U1077   135038       2            2               1         2.0
2  U1077   132825       2            2               2         2.0
3  U1077   135060       1            2               2         2.0
4  U1068   135104       1            1               2         1.0
5  U1068   132740       0            0               0         0.0
6  U1068   132663       1            1               1         1.0
7  U1068   132732       0            0               0         0.0
8  U1068   132630       1            1               1         1.0
9  U1067   132584       2            2               2         2.0

In [2]:
odi = pd.read_csv("odi-batting.csv")
odi

,Country,Player,Runs,MatchDate,Weekday,Ground,Versus,Balls
0,Afghanistan,Mohammad Shahzad,118,16-02-2010,Tue,Sharjah CA Stadium,Canada,121
1,Afghanistan,Mohammad Shahzad,110,01-09-2009,Tue,VRA Ground,Netherlands,111
2,Afghanistan,Mohammad Shahzad,100,16-08-2010,Mon,Cambusdoon New Ground,Scotland,72
3,Afghanistan,Mohammad Shahzad,82,10-07-2010,Sat,Hazelaarweg,Netherlands,108
4,Afghanistan,Mohammad Shahzad,57,01-07-2010,Thu,Sportpark Westvliet,Canada,57
...,...,...,...,...,...,...,...,...
50279,Zimbabwe,Kevin G Duers,5,10-03-1992,Tue,Manuka Oval,South Africa,10
50280,Zimbabwe,Kevin G Duers,2,14-03-1992,Sat,Bellerive Oval,Australia,10
50281,Zimbabwe,Ujesh Ranchod,3,03-02-1993,Wed,Sharjah CA Stadium,Sri Lanka,6
50282,Zimbabwe,Brian V Vitori,3,14-09-2011,Wed,Harare Sports Club,Pakistan,3
50283,Zimbabwe,Waddington Mwayenga,1,29-05-2004,Sat,Harare Sports Club,Australia,2

In [3]:
df = pd.DataFrame(odi)
df

,Country,Player,Runs,MatchDate,Weekday,Ground,Versus,Balls
0,Afghanistan,Mohammad Shahzad,118,16-02-2010,Tue,Sharjah CA Stadium,Canada,121
1,Afghanistan,Mohammad Shahzad,110,01-09-2009,Tue,VRA Ground,Netherlands,111
2,Afghanistan,Mohammad Shahzad,100,16-08-2010,Mon,Cambusdoon New Ground,Scotland,72
3,Afghanistan,Mohammad Shahzad,82,10-07-2010,Sat,Hazelaarweg,Netherlands,108
4,Afghanistan,Mohammad Shahzad,57,01-07-2010,Thu,Sportpark Westvliet,Canada,57
...,...,...,...,...,...,...,...,...
50279,Zimbabwe,Kevin G Duers,5,10-03-1992,Tue,Manuka Oval,South Africa,10
50280,Zimbabwe,Kevin G Duers,2,14-03-1992,Sat,Bellerive Oval,Australia,10
50281,Zimbabwe,Ujesh Ranchod,3,03-02-1993,Wed,Sharjah CA Stadium,Sri Lanka,6
50282,Zimbabwe,Brian V Vitori,3,14-09-2011,Wed,Harare Sports Club,Pakistan,3
50283,Zimbabwe,Waddington Mwayenga,1,29-05-2004,Sat,Harare Sports Club,Australia,2

In [10]:
df.columns

Index(['Country', 'Player', 'Runs', 'MatchDate', 'Weekday', 'Ground', 'Versus',
       'Balls'],
      dtype='object')

In [22]:
mask = df['Runs'] >= 100
filtered_data = df.where(mask)

In [23]:
grouped_data = filtered_data.groupby('Player')

In [24]:
centuries_by_player = grouped_data['Runs'].count()
print(centuries_by_player)

Player
Aamir Sohail              5
Abdool M Samad            1
Abdul Razzaq              3
Abraham B de Villiers    11
Adam C Gilchrist         16
                         ..
Xavier M Marshall         1
Yasir Hameed              3
Younis Khan               6
Yusuf K Pathan            2
Yuvraj Singh             13
Name: Runs, Length: 280, dtype: int64

In [27]:

centuries_by_player.nlargest(3)

Player
Sachin R Tendulkar     48
Ricky T Ponting        30
Sanath T Jayasuriya    28
Name: Runs, dtype: int64

In [41]:
df["StrikeRate"] = df["Runs"] / df["Balls"]
df

,Country,Player,Runs,MatchDate,Weekday,Ground,Versus,Balls,Centuries,StrikeRate
0,Afghanistan,Mohammad Shahzad,118,16-02-2010,Tue,Sharjah CA Stadium,Canada,121,1.0,0.975207
1,Afghanistan,Mohammad Shahzad,110,01-09-2009,Tue,VRA Ground,Netherlands,111,1.0,0.990991
2,Afghanistan,Mohammad Shahzad,100,16-08-2010,Mon,Cambusdoon New Ground,Scotland,72,1.0,1.388889
3,Afghanistan,Mohammad Shahzad,82,10-07-2010,Sat,Hazelaarweg,Netherlands,108,0.0,0.759259
4,Afghanistan,Mohammad Shahzad,57,01-07-2010,Thu,Sportpark Westvliet,Canada,57,0.0,1.000000
...,...,...,...,...,...,...,...,...,...,...
50279,Zimbabwe,Kevin G Duers,5,10-03-1992,Tue,Manuka Oval,South Africa,10,0.0,0.500000
50280,Zimbabwe,Kevin G Duers,2,14-03-1992,Sat,Bellerive Oval,Australia,10,0.0,0.200000
50281,Zimbabwe,Ujesh Ranchod,3,03-02-1993,Wed,Sharjah CA Stadium,Sri Lanka,6,0.0,0.500000
50282,Zimbabwe,Brian V Vitori,3,14-09-2011,Wed,Harare Sports Club,Pakistan,3,0.0,1.000000
50283,Zimbabwe,Waddington Mwayenga,1,29-05-2004,Sat,Harare Sports Club,Australia,2,0.0,0.500000

In [42]:
mask_by_century = df['Runs'] >= 100
filtered_data_by_century = df.where(mask)

In [48]:
filtered_data_by_century

Index(['Country', 'Player', 'Runs', 'MatchDate', 'Weekday', 'Ground', 'Versus',
       'Balls', 'Centuries', 'StrikeRate'],
      dtype='object')

In [49]:
grouped_data_by_century = filtered_data_by_century.groupby('Player')

In [50]:
high_strike_rate_player_by_centuries = grouped_data_by_century['StrikeRate'].sum()
print(high_strike_rate_player_by_centuries)

Player
Aamir Sohail              4.221712
Abdool M Samad            1.040000
Abdul Razzaq              3.385819
Abraham B de Villiers    13.599380
Adam C Gilchrist         18.478741
                           ...
Xavier M Marshall         1.330508
Yasir Hameed              2.532731
Younis Khan               6.161500
Yusuf K Pathan            2.781250
Yuvraj Singh             14.845271
Name: StrikeRate, Length: 280, dtype: float64

In [51]:
high_strike_rate_player_by_centuries.nlargest(3)

Player
Sachin R Tendulkar     48.623615
Sanath T Jayasuriya    32.629685
Ricky T Ponting        30.171934
Name: StrikeRate, dtype: float64

In [54]:
df['Year'] =  pd.DatetimeIndex(df['MatchDate']).year
df

/var/folders/10/jmd1sr_56tqg7b8dv_2wxph80000gp/T/ipykernel_8844/147775358.py:1: UserWarning: Parsing dates in DD/MM/YYYY format when dayfirst=False (the default) was specified. This may lead to inconsistently parsed dates! Specify a format to ensure consistent parsing.
  df['Year'] =  pd.DatetimeIndex(df['MatchDate']).year

,Country,Player,Runs,MatchDate,Weekday,Ground,Versus,Balls,Centuries,StrikeRate,Year
0,Afghanistan,Mohammad Shahzad,118,16-02-2010,Tue,Sharjah CA Stadium,Canada,121,1.0,0.975207,2010
1,Afghanistan,Mohammad Shahzad,110,01-09-2009,Tue,VRA Ground,Netherlands,111,1.0,0.990991,2009
2,Afghanistan,Mohammad Shahzad,100,16-08-2010,Mon,Cambusdoon New Ground,Scotland,72,1.0,1.388889,2010
3,Afghanistan,Mohammad Shahzad,82,10-07-2010,Sat,Hazelaarweg,Netherlands,108,0.0,0.759259,2010
4,Afghanistan,Mohammad Shahzad,57,01-07-2010,Thu,Sportpark Westvliet,Canada,57,0.0,1.000000,2010
...,...,...,...,...,...,...,...,...,...,...,...
50279,Zimbabwe,Kevin G Duers,5,10-03-1992,Tue,Manuka Oval,South Africa,10,0.0,0.500000,1992
50280,Zimbabwe,Kevin G Duers,2,14-03-1992,Sat,Bellerive Oval,Australia,10,0.0,0.200000,1992
50281,Zimbabwe,Ujesh Ranchod,3,03-02-1993,Wed,Sharjah CA Stadium,Sri Lanka,6,0.0,0.500000,1993
50282,Zimbabwe,Brian V Vitori,3,14-09-2011,Wed,Harare Sports Club,Pakistan,3,0.0,1.000000,2011
50283,Zimbabwe,Waddington Mwayenga,1,29-05-2004,Sat,Harare Sports Club,Australia,2,0.0,0.500000,2004

In [60]:
mask_by_country = df.loc[df["Country"] == "India", :]
mask_by_country

,Country,Player,Runs,MatchDate,Weekday,Ground,Versus,Balls,Centuries,StrikeRate,Year
13601,India,Sachin R Tendulkar,200,24-02-2010,Wed,Captain Roop Singh Stadium,South Africa,147,1.0,1.360544,2010
13602,India,Sachin R Tendulkar,186,08-11-1999,Mon,Lal Bahadur Shastri Stadium,New Zealand,150,1.0,1.240000,1999
13603,India,Sachin R Tendulkar,175,05-11-2009,Thu,Rajiv Gandhi International Stadium,Australia,141,1.0,1.241135,2009
13604,India,Sachin R Tendulkar,163,08-03-2009,Sun,AMI Stadium,New Zealand,133,1.0,1.225564,2009
13605,India,Sachin R Tendulkar,152,23-02-2003,Sun,City Oval,Namibia,151,1.0,1.006623,2003
...,...,...,...,...,...,...,...,...,...,...,...
19645,India,Rajinder S Ghai,1,26-01-1986,Sun,Adelaide Oval,Australia,3,0.0,0.333333,1986
19646,India,Nandlal S Yadav,1,09-02-1986,Sun,Melbourne Cricket Ground,Australia,14,0.0,0.071429,1986
19647,India,Naman V Ojha,1,05-06-2010,Sat,Harare Sports Club,Sri Lanka,7,0.0,0.142857,2010
19648,India,Sudeep Tyagi,1,27-02-2010,Sat,Sardar Patel Stadium,South Africa,2,0.0,0.500000,2010
19649,India,Yograj Singh,1,14-02-1981,Sat,Eden Park,New Zealand,3,0.0,0.333333,1981

In [61]:
mask_india_player_century = mask_by_country.loc[mask_by_country["Runs"] >= 100, :]
mask_india_player_century

,Country,Player,Runs,MatchDate,Weekday,Ground,Versus,Balls,Centuries,StrikeRate,Year
13601,India,Sachin R Tendulkar,200,24-02-2010,Wed,Captain Roop Singh Stadium,South Africa,147,1.0,1.360544,2010
13602,India,Sachin R Tendulkar,186,08-11-1999,Mon,Lal Bahadur Shastri Stadium,New Zealand,150,1.0,1.240000,1999
13603,India,Sachin R Tendulkar,175,05-11-2009,Thu,Rajiv Gandhi International Stadium,Australia,141,1.0,1.241135,2009
13604,India,Sachin R Tendulkar,163,08-03-2009,Sun,AMI Stadium,New Zealand,133,1.0,1.225564,2009
13605,India,Sachin R Tendulkar,152,23-02-2003,Sun,City Oval,Namibia,151,1.0,1.006623,2003
...,...,...,...,...,...,...,...,...,...,...,...
18180,India,Yusuf K Pathan,123,07-12-2010,Tue,M.Chinnaswamy Stadium,New Zealand,96,1.0,1.281250,2010
18181,India,Yusuf K Pathan,105,23-01-2011,Sun,Supersport Park,South Africa,70,1.0,1.500000,2011
18244,India,Raman Lamba,102,07-10-1986,Tue,Madhavrao Scindia Cricket Ground,Australia,120,1.0,0.850000,1986
18467,India,Woorkeri V Raman,114,11-12-1992,Fri,Supersport Park,South Africa,148,1.0,0.770270,1992
18636,India,Chetan Sharma,101,25-10-1989,Wed,Green Park,England,96,1.0,1.052083,1989

In [64]:
grouped_data_by_year = mask_india_player_century.groupby('Year')

In [65]:
max_runs_scored_in_year = grouped_data_by_year['Runs'].sum()
print(max_runs_scored_in_year)

Year
1983     175
1984     309
1986     204
1987     440
1988     523
1989     209
1990     313
1991     214
1992     114
1993     234
1994     758
1995     112
1996     913
1997     771
1998    2135
1999    1998
2000    1252
2001    1047
2002    1062
2003    1130
2004     831
2005    1307
2006     556
2007     575
2008    1140
2009    1749
2010    1444
2011     943
Name: Runs, dtype: int64

In [67]:
max_runs_scored_in_year.nlargest(3)

Year
1998    2135
1999    1998
2009    1749
Name: Runs, dtype: int64

In [68]:
# Description
# The given dataset 'order' has a variable 'Order_Date' with the dates of purchase.
# Create a new variable 'day' which will contain the day from the date at variable Order_Date.
# Execution Time Limit

import pandas as pd
order = pd.read_csv('https://media-doselect.s3.amazonaws.com/generic/0gjkvLLgNdQLqG10jo5yyJyjK/orders_dimen.csv')
order['Order_Date'] = pd.to_datetime(order['Order_Date'])

order['day'] = pd.DatetimeIndex(order['Order_Date']).day

print(order.head(10))

   Order_ID Order_Date Order_Priority  Ord_id  day
0         3 2010-10-13            LOW   Ord_1   13
1       293 2012-01-10           HIGH   Ord_2   10
2       483 2011-10-07           HIGH   Ord_3    7
3       515 2010-08-28  NOT SPECIFIED   Ord_4   28
4       613 2011-06-17           HIGH   Ord_5   17
5       643 2011-03-24           HIGH   Ord_6   24
6       678 2010-02-26            LOW   Ord_7   26
7       807 2010-11-23         MEDIUM   Ord_8   23
8       868 2012-08-06  NOT SPECIFIED   Ord_9    6
9       933 2012-04-08  NOT SPECIFIED  Ord_10    8

/var/folders/10/jmd1sr_56tqg7b8dv_2wxph80000gp/T/ipykernel_8844/3685455881.py:8: UserWarning: Parsing dates in DD/MM/YYYY format when dayfirst=False (the default) was specified. This may lead to inconsistently parsed dates! Specify a format to ensure consistent parsing.
  order['Order_Date'] = pd.to_datetime(order['Order_Date'])

In [ ]:
ma